#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HelloWorld.Droid.Resource", IsApplication=true)]

namespace HelloWorld.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int green = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int saddlebrown = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int abraham_lincoln = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bill_gates = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int charles_darwin = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int charles_de_gaulle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int christopher_columbus = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int george_orwell = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int john_kennedy = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int mahatma_gandhi = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int margaret_thatcher = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int marilyn_monroe = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int martin_luther_king = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int mother_teresa = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int muhammad_ali = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int nelson_mandela = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Splash = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int winston_churchill = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int greetingButton = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int greetingTextView = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int listItem = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int name = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int nameEditText = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int nameListButton = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int picture = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int promptTextView = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int year = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NameListItem = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MyTheme_Splash = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
